spring:
  datasource:
    # 指定MySQL JDBC驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 指定MySQL连接URL，以及设置编码和时区
    url: jdbc:mysql://43.139.111.55:3306/lion_code?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    # 指定MySQL用户名
    username: root
    # 指定MySQL密码
    password: root
    # 指定德鲁伊数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 指定连接池初始化大小
      initial-size: 1
      # 指定连接池最小空闲连接数
      min-idle: 5
      # 指定连接池最大连接数
      max-active: 20
      # 指定获取连接时的最大等待时间，单位毫秒
      max-wait: 60000
      # 配置检测需要关闭的空闲连接时间，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位毫秒
      min-evictable-idle-time-millis: 300000
      # 指定验证查询语句，用于测试连接是否有效
      validation-query: SELECT 1
      # 指定验证查询超时时间，单位毫秒
      validation-query-timeout: 3000
      # 配置连接空闲时是否进行测试，如果为true，则空闲连接将被测试
      test-while-idle: true
      # 配置获取连接时是否进行测试，如果为true，则每次获取连接时都会测试连接是否有效
      test-on-borrow: false
      # 配置归还连接时是否进行测试，如果为true，则归还连接时都会测试连接是否有效
      test-on-return: false
      # 指定德鲁伊的过滤器，用于监控、防火墙、日志等等
      filters: stat,wall,logback
  management:
    endpoints:
      web:
        base-path: /actuator
    startup:
      report-location: report.txt


logging:
  level:
    root: INFO

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080 # 服务器监听端口号
  undertow:
    io-threads: 4 # I/O线程数
    worker-threads: 10 # 工作线程数
    direct-buffers: true # 是否使用直接缓冲区
    buffer-pool: # 缓冲池配置
      buffers-per-region: 10 # 每个区域的缓冲区数量
      buffer-size: 16384 # 缓冲区大小
      max-regions: 10 # 最大区域数
    server-options: # 服务器选项配置
      server-header: Undertow # 服务器响应头
      max-concurrent-requests: 100 # 最大并发请求数
      max-connections: 500 # 最大连接数
      request-parse-timeout: 5000 # 请求解析超时时间（毫秒）
      max-entity-size: 10485760 # 最大请求体大小（字节）
      http2-allow-unsafe-practices: true # 是否允许不安全的HTTP/2行为
    access-log: # 访问日志配置
      enabled: true # 是否启用访问日志
      prefix: access_log # 访问日志文件名前缀
      suffix: .log # 访问日志文件名后缀
      dir: ../../log/undertow/ # 访问日志文件保存目录
      rotate: on # 访问日志文件轮转方式（按天、按小时、按分钟等）
    http-listeners: # HTTP监听器配置
      - socket-binding: http # 监听器使用的socket-binding名称
        redirect-socket: https # 是否启用重定向到HTTPS
        enable-http2: true # 是否启用HTTP/2
    https-listeners: # HTTPS监听器配置
      - socket-binding: https # 监听器使用的socket-binding名称
        security-realm: SSLRealm # 安全领域名称
        verify-client: true # 是否启用客户端证书验证
        enable-http2: true # 是否启用HTTP/2
    servlet-container: # Servlet容器配置
      default-buffer-cache: # 默认缓冲池配置
        size: 1024 # 缓冲池大小
        buffers-per-region: 10 # 每个区域的缓冲区数量
        max-regions: 10 # 最大区域数
      session: # Session配置
        persistent: true # 是否启用Session持久化
        persistent-store: /var/lib/undertow/sessions # Session持久化存储路径
        cookie-name: JSESSIONID # Session ID在Cookie中的名称
        timeout: 30m # Session超时时间
      jsp: # JSP配置
        development: true # 是否启用JSP开发模式
        check-interval: 0 # JSP检查间隔时间（秒）
        modification-test-interval: 4 # JSP修改检查间隔时间（秒）
        reload-on-missing-class: true # 是否在缺少类文件时重新加载JSP页面
